"""
Sample analysis text with Markdown formatting for testing.
"""

SAMPLE_ANALYSIS_MARKDOWN = """
## 1. Chart Type & Visual Elements

This is a **vertical bar chart** displaying product sales data. The visualization uses:

- **X-axis**: Categorical product names (nominal scale)
- **Y-axis**: Total sales values (quantitative scale)  
- **Bars**: Height represents aggregated sales per product

### Visual Encodings

The chart employs several effective visual encodings:

1. Position (X): Product categories
2. Length (Y): Sales magnitude  
3. Color: Single color scheme for clarity

---

## 2. Data Insights

### Key Patterns

> **Important**: Product A shows significantly higher sales compared to others.

The data reveals several important patterns:

- **Product A**: Dominant market leader (~$280K sales)
- **Product B**: Second position (~$180K sales)
- **Product C**: Third position (~$120K sales)

### Trends

Sales distribution shows a clear **descending pattern**:

```
Product A >>> Product B > Product C
```

---

## 3. Key Findings

### Primary Observations

1. **Market Concentration**: Top product accounts for ~45% of total sales
2. **Significant Gap**: 55% difference between top and bottom products  
3. **Opportunity**: Products B and C have growth potential

### Data Quality

- ✅ No missing values detected
- ✅ Consistent data format
- ⚠️ Consider temporal analysis for trends

---

## 4. Recommendations

### Immediate Actions

1. **Double down on Product A**
   - Increase inventory
   - Expand marketing budget
   - Monitor stock levels

2. **Investigate Product C**  
   - Identify barriers to sales
   - Customer feedback analysis
   - Pricing strategy review

3. **Benchmark Competition**
   - Compare against industry standards
   - Identify best practices
   - Set realistic growth targets

### Long-term Strategy

> Focus on diversification to reduce dependency on single product

**Next Steps**:
- Conduct deep-dive analysis on Product A success factors
- A/B test pricing strategies for Product C
- Develop cross-selling opportunities between products

---

*Analysis generated by GLM-4V Vision Model*  
*Last updated: 2025-10-30*
"""
